name: Modern Robotics Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/src

    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Build package
      working-directory: ${{ github.workspace }}/src
      run: cargo build --release

    - name: Test
      working-directory: ${{ github.workspace }}/src
      run: cargo test

    - name: Upload built package
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/src/target
        name: modern-robotics-rs

  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/src

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Test
        working-directory: ${{ github.workspace }}/src
        run: cargo test

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/src

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build package
        working-directory: ${{ github.workspace }}/src
        run: cargo doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/target/doc/modern_robotics
          force_orphan: true
