# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Modern Robotics Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/src

    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Build package
      working-directory: ${{ github.workspace }}/src
      run: cargo build --release

    - name: Test
      working-directory: ${{ github.workspace }}/src
      run: cargo test

    - name: Upload built package
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/src/target
        name: modern-robotics-rs
